name: Sync streamlit-image-classification from Upstream

on:
  schedule:
    - cron: "10 9 * * *"   # daily at 09:10 UTC
  workflow_dispatch:

jobs:
  sync:
    uses: 2ai-lab/.github/.github/workflows/reusable-sync-upstream.yml@main
    with:
      upstream_url: https://github.com/2ai-lab/streamlit-image-classification.git
      mode: "push"   # change to "pr" if branch protected
    secrets:
      # push_token: ${{ secrets.PAT }}   # enable if private repo / special permissions
